# Generated by Django 4.2.11 on 2024-03-17 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='rate',
            field=models.CharField(default=100, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
